version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: optima-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: optima
      POSTGRES_PASSWORD: optima
      POSTGRES_DB: optima
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  adminer:
    image: adminer:4
    container_name: optima-adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db
    depends_on:
      - db

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: optima-web
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://optima:optima@db:5432/optima?schema=public
      - NODE_ENV=development
      - NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME=${NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME}
      - NEXT_PUBLIC_CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - db

volumes:
  db-data:


